language: python
sudo: required
dist: trusty
python:
  - "3.5"
install:
  - pip3 install numpy
  - pip3 install pandas
  - pip3 install tensorflow
  - pip3 install tweepy
  - pip3 install unittest2
  - pip3 install textblob
  - python3 -m textblob.download_corpora
script: python3 src/test/test_all.py